name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # or your preferred Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: false  # This prevents treats warnings as errors

      - name: Deploy to GitHub Pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: out  # Next.js static export directory
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}